2 login feature
mfathulqorib/bytehub-event-organizer pull request #3
Opened 2023-11-28 06:48 UTC by kemalmao19

add functionally login feature

2023-11-28 12:02 UTC, indrazm commented on src/app/(auth)/login/page.js
> +    <>
You don't need a fragment <>

2023-11-28 12:02 UTC, indrazm commented on src/components/auth/components/Icons/PasswdIcon.jsx
> +export const PasswdIcon = (props) => (
It doesn't need any props

2023-11-28 12:03 UTC, indrazm commented on src/components/auth/components/Login.jsx
> +    <main className='flex flex-col justify-between items-center py-5' style={{height:"100vh"}}>
change `style={{ height: "100vh"}}` to `h-screen` class.

2023-11-28 12:04 UTC, indrazm requested changes
Please change. 
Many Thanks.

2023-11-28 13:04 UTC, indrazm approved these changes
lgtm.

2023-11-29 09:02 UTC, agungagriza approved these changes

2023-11-29 14:42 UTC, merged